#!/usr/bin/env python3
"""YAML-driven Yocto build orchestrator for the RPi4 image.

Reads project.yml, fetches pinned layers, generates BitBake configuration,
templates the custom layer's network/console files, and runs bitbake.
"""

import ipaddress
import re
import subprocess
import sys
from pathlib import Path

import yaml


class ConfigError(Exception):
    """Raised when project.yml is invalid; message names the offending key."""


USERNAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")

REQUIRED_KEYS = ["name", "machine", "image", "distro", "layers",
                 "user", "network", "console"]


def _require(cfg, dotted_key):
    node = cfg
    for part in dotted_key.split("."):
        if not isinstance(node, dict) or part not in node:
            raise ConfigError(f"missing required key: {dotted_key}")
        node = node[part]
    return node


def _check_ipv4(value, dotted_key):
    try:
        ipaddress.IPv4Address(value)
    except (ipaddress.AddressValueError, ValueError):
        raise ConfigError(f"invalid IPv4 address for {dotted_key}: {value!r}")


def validate_config(cfg):
    if not isinstance(cfg, dict):
        raise ConfigError("top-level YAML must be a mapping")
    for key in REQUIRED_KEYS:
        _require(cfg, key)

    for layer in cfg["layers"]:
        name = layer.get("name", "<unnamed>")
        if "path" in layer:
            continue
        if "url" not in layer or "branch" not in layer:
            raise ConfigError(
                f"layer {name!r} needs either 'path' or 'url' + 'branch'")

    username = _require(cfg, "user.name")
    if not USERNAME_RE.match(str(username)):
        raise ConfigError(f"invalid POSIX username for user.name: {username!r}")
    _require(cfg, "user.password")

    for key in ("network.interface", "network.gateway"):
        _require(cfg, key)
    _check_ipv4(_require(cfg, "network.address"), "network.address")
    _check_ipv4(_require(cfg, "network.gateway"), "network.gateway")

    netmask = _require(cfg, "network.netmask")
    try:
        ipaddress.IPv4Network(f"0.0.0.0/{netmask}")
    except (ipaddress.NetmaskValueError, ValueError):
        raise ConfigError(f"invalid netmask for network.netmask: {netmask!r}")

    dns = _require(cfg, "network.dns")
    if not isinstance(dns, list) or not dns:
        raise ConfigError("network.dns must be a non-empty list")
    for entry in dns:
        _check_ipv4(entry, "network.dns")

    _require(cfg, "console.keymap")
    _require(cfg, "console.font")


def load_config(path):
    with open(path, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)
    validate_config(cfg)
    return cfg


def hash_password(password, salt=None):
    """SHA-512 crypt via openssl; avoids the crypt module removed in 3.13.

    The crypt salt alphabet is [./a-zA-Z0-9], so the result can never
    contain '{' and is safe to embed in BitBake conf files.
    """
    cmd = ["openssl", "passwd", "-6", "-stdin"]
    if salt is not None:
        cmd[3:3] = ["-salt", salt]
    result = subprocess.run(cmd, input=password + "\n", capture_output=True,
                            text=True, check=True)
    return result.stdout.strip()


def netmask_to_prefix(netmask):
    return ipaddress.IPv4Network(f"0.0.0.0/{netmask}").prefixlen


GENERATED_HEADER = "# Generated by build.py from project.yml -- do not edit by hand.\n"

IMAGE_EXTRA_PACKAGES = "sudo sudo-group-conf kbd kbd-keymaps terminus-font-consolefonts"


def _extra_users_params(cfg, password_hash):
    user = cfg["user"]
    parts = []
    if user.get("sudo", False):
        parts.append("groupadd -f sudo;")
        group_opt = " -G sudo"
    else:
        group_opt = ""
    parts.append(
        f"useradd -m -s /bin/bash{group_opt} -p '{password_hash}' {user['name']};")
    if cfg.get("root", {}).get("disable_login", True):
        parts.append("usermod -L root;")
    return " ".join(parts)


def generate_local_conf(cfg, password_hash):
    lines = [
        GENERATED_HEADER,
        f'MACHINE = "{cfg["machine"]}"',
        f'DISTRO = "{cfg["distro"]}"',
        'INIT_MANAGER = "systemd"',
        '',
        'IMAGE_FSTYPES = "wic.bz2 wic.bmap"',
        '',
        'INHERIT += "extrausers"',
        f'EXTRA_USERS_PARAMS = "{_extra_users_params(cfg, password_hash)}"',
        '',
        f'IMAGE_INSTALL:append = " {IMAGE_EXTRA_PACKAGES}"',
        '',
        'CONF_VERSION = "2"',
    ]
    lines += cfg.get("local_conf_extra") or []
    return "\n".join(lines) + "\n"


def layer_dirs(cfg, repo_root):
    dirs = []
    for layer in cfg["layers"]:
        if "path" in layer:
            dirs.append(repo_root / layer["path"])
        else:
            base = repo_root / "layers" / layer["name"]
            for sub in layer.get("layers") or [None]:
                dirs.append(base / sub if sub else base)
    return dirs


def generate_bblayers_conf(cfg, repo_root):
    entries = "".join(f"  {d} \\\n" for d in layer_dirs(cfg, repo_root))
    return (
        GENERATED_HEADER
        + 'POKY_BBLAYERS_CONF_VERSION = "2"\n'
        + 'BBPATH = "${TOPDIR}"\n'
        + 'BBFILES ?= ""\n'
        + 'BBLAYERS ?= " \\\n'
        + entries
        + '"\n'
    )


def generate_network_file(cfg):
    net = cfg["network"]
    prefix = netmask_to_prefix(net["netmask"])
    dns_lines = "".join(f"DNS={entry}\n" for entry in net["dns"])
    return (
        f"[Match]\nName={net['interface']}\n\n"
        f"[Network]\nAddress={net['address']}/{prefix}\n"
        f"Gateway={net['gateway']}\n{dns_lines}"
    )


def generate_vconsole_conf(cfg):
    console = cfg["console"]
    return f"KEYMAP={console['keymap']}\nFONT={console['font']}\n"


class FetchError(Exception):
    """Raised when a layer checkout cannot be safely updated."""


def _git(repo, *args):
    return subprocess.run(["git", "-C", str(repo), *args],
                          check=True, capture_output=True, text=True)


def fetch_layers(cfg, layers_dir):
    for layer in cfg["layers"]:
        if "path" in layer:
            continue
        dest = Path(layers_dir) / layer["name"]
        branch = layer["branch"]
        if not dest.exists():
            print(f"Cloning {layer['name']} ({branch})...")
            subprocess.run(["git", "clone", "--branch", branch,
                            layer["url"], str(dest)], check=True)
        else:
            status = _git(dest, "status", "--porcelain").stdout
            if status.strip():
                raise FetchError(
                    f"layer checkout {layer['name']} at {dest} has local "
                    f"changes; commit/stash them or remove the directory")
            print(f"Updating {layer['name']} ({branch})...")
            _git(dest, "fetch", "origin")
        if "rev" in layer:
            _git(dest, "checkout", "--detach", layer["rev"])
        else:
            _git(dest, "checkout", "-B", branch, f"origin/{branch}")


def write_outputs(cfg, repo_root):
    repo_root = Path(repo_root)
    conf_dir = repo_root / "build" / "conf"
    conf_dir.mkdir(parents=True, exist_ok=True)

    password_hash = hash_password(cfg["user"]["password"])
    (conf_dir / "local.conf").write_text(
        generate_local_conf(cfg, password_hash))
    (conf_dir / "bblayers.conf").write_text(
        generate_bblayers_conf(cfg, repo_root))

    files_dir = (repo_root / "meta-rpi4-custom" / "recipes-core"
                 / "systemd-conf" / "files")
    (files_dir / "10-static.network").write_text(generate_network_file(cfg))
    (files_dir / "vconsole.conf").write_text(generate_vconsole_conf(cfg))


if __name__ == "__main__":
    sys.exit(0)  # replaced by main() in a later task
